apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-k8s-config
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "secrets/config_dec.yml").AsSecrets | indent 2 }}