{
 "title": "[DEV] trading_bot_api",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "api_path", "label": "API Path", "query": { "query": "trading_bot_api_requests_total" } }
  ]
 },
 "panels": [
  { "title": "k8s", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "container api-api",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_ready{namespace=\"app-dev\", container=\"api-api\"}) by (container)"
    }
   ]
  },
  {
   "title": "container api-consumer",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_ready{namespace=\"app-dev\", container=\"api-consumer\"}) by (container)"
    }
   ]
  },
  {
   "title": "Container Runtime Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{pod=~\"api-.*\", namespace=\"app-dev\", reason!=\"Completed\"}) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "min(time() - kube_pod_start_time{namespace=\"app-dev\", pod=~\"api-.*\"}) by (namespace, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PODs restarts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"api-.*\", namespace=\"app-dev\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Waiting Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{pod=~\"api-.*\", namespace=\"app-dev\", reason!=\"ContainerCreating\"}) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "CPU api-api",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"api-.*\", image!=\"\", container=\"api-api\"}[$__rate_interval])",
     "legendFormat": "api-api {{pod}}"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"api-.*\", container=\"api-api\", image!=\"\"}[$__rate_interval])",
     "legendFormat": "throttling api-api {{pod}}"
    }
   ]
  },
  {
   "title": "CPU api-consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"api-.*\", image!=\"\", container=~\"api-consumer\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"api-.*\", container=\"api-consumer\", image!=\"\"}[$__rate_interval])",
     "legendFormat": "throttling {{pod}}"
    }
   ]
  },
  {
   "title": "RAM api-api",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"api.*\", image!=\"\", container=\"api-api\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RAM api-consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"api.*\", image!=\"\", container=\"api-api\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "4xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(trading_bot_api_responses_total{status=~\"4..\"}[$__rate_interval])) by (path, status, method)",
     "legendFormat": "{{status}} : {{path}} : {{method}}"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(trading_bot_api_responses_total{status=~\"5..\"}[$__rate_interval])) by (path, status)",
     "legendFormat": "{{status}} : {{path}}"
    }
   ]
  },
  { "title": "$api_path", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }, "repeat": "api_path" },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(trading_bot_api_requests_total{path=\"$api_path\"}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Response Timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(trading_bot_api_response_duration_seconds_bucket{path=\"$api_path\"}[$__rate_interval])) by (le))",
     "legendFormat": "q95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(trading_bot_api_response_duration_seconds_bucket{path=\"$api_path\"}[$__rate_interval])) by (le))",
     "legendFormat": "q50"
    },
    {
     "expr": "sum(rate(trading_bot_api_response_duration_seconds_sum{path=\"$api_path\"}[$__rate_interval])) / sum(rate(trading_bot_api_response_duration_seconds_count{path=\"$api_path\"}[$__rate_interval]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (increase(trading_bot_api_responses_total{path=\"$api_path\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}